### ISSUE TITLE
Probleme d'apel au menu gps..

### ISSUE THREAD

**Issue by Gbutome** [AmauryD/A3GPS#12]
je n'arrive pas a configurer l'appel du gps...
Dans quel fichier faut il le mettre? moi je l'ai mis dans : "initPlayerLocal.sqf"

J'ai mis ceci:
`if (hasInterface) then {
	player addAction ["Open GPS",gps_menu_fnc_loadGPSMenu];
};`

Mais sa m'envoi cette erreur ci:  

`Warning Message: Resource GPS_MENU not found`

Help me please

**Comment by Gbutome** [comment]
Salut, oui c'est ok... Probleme résolu*
merci de m'avoir repondu
;)

**Comment by AmauryD** [comment]
Oki , pas de soucis :D

**Comment by MaxQc11** [comment]
salut jai le meme probleme :S mais je n'utlise pas le meme chemin j'essaie d'ouvrir le gps par le meny y esque cest possible ?

**Comment by AmauryD** [comment]
@MaxQc11 Tu as le GPS de The-Programmer ou l'original ?

**Comment by mecta02** [comment]
je deterre le post ou a tu entrée la valeur       if (hasInterface) then { player addAction ["Open GPS",gps_menu_fnc_loadGPSMenu]; };      stp
