### ISSUE TITLE
Probleme de priorité ?

### ISSUE THREAD

**Issue by code34** [AmauryD/A3GPS#7]
Du centre d'agios pour aller à l'est de Kavala (en 049129), l'algo passe par Kavala au lieu de passer par le grande route au nord tout de suite à gauche de l'usine.

**Comment by AmauryD** [comment]
Je vais voir ça mais ça peut aussi être lié au bug #5

**Comment by AmauryD** [comment]
![gps](https://user-images.githubusercontent.com/9933000/34640188-480ea480-f2ee-11e7-8236-97ac04d55871.PNG)
C'est bien ça , les routes ne sont pas considérées comme connectées à cet endroit là , je vais essayer de fix ça dans les prochains jours.

**Comment by code34** [comment]
j avais déjà constaté ce type de problème car cela pertube l'IA ://

Je ne comprends pas pk BIS n'a pas corrigé le problème depuis le temps.

**Comment by Sparker95** [comment]
Hello! Once i have encountered a similar issue: IIRC, roadsConnectedTo doesn't always recognize crossroads, or something like that. It dissappointed me very much and broke my plans, so it's of my interest as well if it's possible to find a solution to this problem.
Am I right that you use roadsConnectedTo to find crossroads? Sorry, I didn't look deep in the code yet.
Also, the fact that it also affects AIs is new to me. Do you mean that when they do their pathfinding they can also ignore this road intersection and choose a weird non-optimal route, similar to what this GPS Navigator mod gives?

**Comment by AmauryD** [comment]
Hello Sparker , i partially fixed the problem , for each road i check if the road has a road (in a 15 meters radius) with 1 connected road , if it's the case i link them to each other.[ (fn_mapRoutes line 33)](https://github.com/AmauryD/A3GPS/blob/master/A3GPS/gps/fn_mapRoutes.sqf)
In the future i will try to check if road intersect with each other with [this function](https://github.com/AmauryD/A3GPS/blob/master/A3GPS/misc/fn_getRoadBoundingBoxWorld.sqf).
I don't know for the real AI pathfinding , i'll check later.
