### ISSUE TITLE
fn_tracking.sqf - dir

### ISSUE THREAD

**Issue by code34** [AmauryD/A3GPS#9]
Hello

J'ai regardé ce code:
[https://github.com/AmauryD/A3GPS/blob/master/A3GPS/gps/fn_tracking.sqf](tracking)

et je me demande à quoi sert exactement:
`
if (_dir >= 135 && _dir <= 225) exitWith {
	_path deleteAt (_path find _next_node);
};
`

et pourquoi ensuite faire un switch sur les valeurs 135 et 225 ?

**Comment by AmauryD** [comment]
Yop , le principe de cette ligne est de supprimer l'élément vu que lorsqu'une direction est comprise entre 135 et 225 , ça veut dire que l'angle n'est pas assez élevé pour qu'il considère ça comme un 'tournant' (il est donc inutile de dire de tourner à gauche ou à droite si ce n'est pas un tournant).

J'avoue que ces lignes sont assez abstraites et son sûrement simplifiables , ce fichier doit être légèrement repensé et refait car j'ai même dur à me souvenir comment le calcul de l'angle est effectué.

**Comment by code34** [comment]
A vrai dire, je ne comprends pas ce calcul d'angle. J'aurais tendance à dire que si l'objet source est décalé sur la gauche par rapport à l'objet cible qui lui fait face, ça devrait indiquer tourner sur la droite.

Mais ça ne fonctionne pas comme cela en fonction de ou se trouve l'objet source par rapport à l'objet cible, dès fois ça marche , dès fois pas.

**Comment by code34** [comment]
est ce que pour toi cela marche normalement ? j'ai une idée de comment procéder mais pas eu le temps de tester.

**Comment by AmauryD** [comment]
ça marche , c'est ça qui est étrange.
J'ai plus trop le temps non plus pour le moment (blocus).

**Comment by code34** [comment]
ok dis moi quand tu reprends sur le sujet. J'ai mis normalement de côté un peu de code sur ce sujet: )

**Comment by AmauryD** [comment]
Je devrais reprendre la semaine prohaine , j'ai déjà épeluché pas mal Google aussi mais rien ne semble donner un résultat correct

**Comment by AmauryD** [comment]
Je me remets au boulot dessus , on devrait se retrouver sur un Teamspeak pour discuter un peu de ça si tu as le temps.

**Comment by code34** [comment]
ça marche :) on a aussi un discord, ou on se rencontre souvent le soir pour parler dev !

https://discord.gg/Js4yny

**Comment by AmauryD** [comment]
J'ai changé la méthode de tracking après tout ce temps , elle est logique cette fois-ci normalement 
commit :  6cefc08

**Comment by code34** [comment]
en survolant ça me semble equivalent à la piste que j'avais regardé. par contre quand je l'avais testé, ça marchait pas très bien. est ce que tu l'as testé avec plusieurs intersections ?
